--USERT SQL
CREATE TABLE USERT 
(
  USERNO NUMBER(10, 0) NOT NULL 
, ID VARCHAR2(50 BYTE) NOT NULL 
, PW VARCHAR2(21 BYTE) NOT NULL 
, PHONE VARCHAR2(20 BYTE) NOT NULL 
, NICKNAME VARCHAR2(20 BYTE) NOT NULL 
, POINT NUMBER(10, 0) DEFAULT 0 NOT NULL 
, GRADE NUMBER(10, 0) DEFAULT 1000 NOT NULL 
, SEX NUMBER(1, 0) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT USERT_PK PRIMARY KEY 
  (
    USERNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USERT_PK ON USERT (USERNO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE USERT
ADD CONSTRAINT UNIQ_USERID UNIQUE 
(
  ID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX UNIQ_USERID ON USERT (ID ASC) 
    LOGGING 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      FREELISTS 1 
      FREELIST GROUPS 1 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

COMMENT ON COLUMN USERT.USERNO IS '회원 번호';
COMMENT ON COLUMN USERT.ID IS '아이디(이메일형식)';
COMMENT ON COLUMN USERT.PW IS '비밀번호';
COMMENT ON COLUMN USERT.PHONE IS '전화번호';
COMMENT ON COLUMN USERT.NICKNAME IS '닉네임';
COMMENT ON COLUMN USERT.POINT IS '보유한 포인트';
COMMENT ON COLUMN USERT.GRADE IS '점수';
COMMENT ON COLUMN USERT.SEX IS '성별';
COMMENT ON COLUMN USERT.NAME IS '이름';

--POSTT SQL
CREATE TABLE POSTT 
(
  POSTNO NUMBER NOT NULL 
, TITLE VARCHAR2(60 BYTE) NOT NULL 
, REGION NUMBER NOT NULL 
, POSTINGDATE VARCHAR2(20 BYTE) NOT NULL 
, CONTENTS VARCHAR2(2000 BYTE) NOT NULL 
, B_HOPEFULPOINT NUMBER NOT NULL 
, STATE NUMBER NOT NULL 
, REQUESTTIME VARCHAR2(20 BYTE) NOT NULL 
, HOWMUCH VARCHAR2(20 BYTE) NOT NULL 
, USERNO NUMBER NOT NULL 
, CONSTRAINT POSTT_PK PRIMARY KEY 
  (
    POSTNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX POSTT_PK ON POSTT (POSTNO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE POSTT
ADD CONSTRAINT FK_POSTT_USERNO FOREIGN KEY
(
  USERNO 
)
REFERENCES USERT
(
  USERNO 
)
ENABLE;

COMMENT ON COLUMN POSTT.POSTNO IS '게시물 번호';
COMMENT ON COLUMN POSTT.TITLE IS '제목';
COMMENT ON COLUMN POSTT.REGION IS '서귀포시or제주시';
COMMENT ON COLUMN POSTT.POSTINGDATE IS ' 게시물작성날짜';
COMMENT ON COLUMN POSTT.CONTENTS IS '게시물내용';
COMMENT ON COLUMN POSTT.B_HOPEFULPOINT IS 'buyer희망 포인트 ';
COMMENT ON COLUMN POSTT.STATE IS '진행상태';
COMMENT ON COLUMN POSTT.REQUESTTIME IS '부탁시간';
COMMENT ON COLUMN POSTT.HOWMUCH IS '부탁 시간 이후 얼마나 기다려야하는지';
COMMENT ON COLUMN POSTT.USERNO IS '회원 번호';

--PAYRECORDT SQL
CREATE TABLE PAYRECORDT 
(
  PAYNO NUMBER NOT NULL 
, PAYAMOUNT NUMBER NOT NULL 
, PAYDATE VARCHAR2(20 BYTE) NOT NULL 
, USERNO NUMBER NOT NULL 
, CONSTRAINT PAYRECORDT_PK PRIMARY KEY 
  (
    PAYNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PAYRECORDT_PK ON PAYRECORDT (PAYNO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE PAYRECORDT
ADD CONSTRAINT FK_PAYRECORD_USERNO FOREIGN KEY
(
  USERNO 
)
REFERENCES USERT
(
  USERNO 
)
ENABLE;

COMMENT ON COLUMN PAYRECORDT.PAYNO IS '결제번호';
COMMENT ON COLUMN PAYRECORDT.PAYAMOUNT IS '결제금액';
COMMENT ON COLUMN PAYRECORDT.PAYDATE IS '결제일';
COMMENT ON COLUMN PAYRECORDT.USERNO IS '회원 번호';

--COMMENTT SQL
CREATE TABLE COMMENTT 
(
  COMMENTNO NUMBER NOT NULL 
, WDATE VARCHAR2(20 BYTE) NOT NULL 
, CONTENTS VARCHAR2(1000 BYTE) NOT NULL 
, SELECTED NUMBER DEFAULT 0 NOT NULL 
, H_HOPEFULPOINT NUMBER NOT NULL 
, USERNO NUMBER NOT NULL 
, POSTNO NUMBER NOT NULL 
, CONSTRAINT COMMENTT_PK PRIMARY KEY 
  (
    COMMENTNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX COMMENTT_PK ON COMMENTT (COMMENTNO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE COMMENTT
ADD CONSTRAINT FK_COMMENT_POSTNO FOREIGN KEY
(
  POSTNO 
)
REFERENCES POSTT
(
  POSTNO 
)
ENABLE;

ALTER TABLE COMMENTT
ADD CONSTRAINT FK_COMMENT_USERNO FOREIGN KEY
(
  USERNO 
)
REFERENCES USERT
(
  USERNO 
)
ENABLE;

COMMENT ON COLUMN COMMENTT.COMMENTNO IS '댓글번호';
COMMENT ON COLUMN COMMENTT.WDATE IS '댓글작성날짜';
COMMENT ON COLUMN COMMENTT.CONTENTS IS '댓글내용';
COMMENT ON COLUMN COMMENTT.SELECTED IS '선택되었는지구분';
COMMENT ON COLUMN COMMENTT.H_HOPEFULPOINT IS 'helper희망 포인트';
COMMENT ON COLUMN COMMENTT.USERNO IS '회원 번호';
COMMENT ON COLUMN COMMENTT.POSTNO IS '게시물 번호';

--시퀀스 생성
CREATE SEQUENCE seq_userno;
CREATE SEQUENCE seq_postno;
CREATE SEQUENCE seq_commentno;
CREATE SEQUENCE sqe_payno;


